### ISSUE TITLE
Not found Unity Editor Directory: /Applications/Unity/Hub/Editor/2018.3.0f2

### ISSUE THREAD

**Issue by vanlecs09** [Dinomite-Studios/unity-build-task#9]
Do i need to set the unity editor directory on my machine?

**Comment by FejZa** [comment]
Hi,

this error indicates that the build task can't find the specified Unity editor version on your agent. Please install Unity Hub on the agent and in the settings check the "Editor Folder Location" path. This is the easiest way to specify where Unity Editors are to be found.

Let's say you want to build using Unity 2018.3.0f1. The task will look for the following path by default then:

C:\Program Files\Unity\Hub\Editor\2018.3.0f1

If it can't find it, you get the above error. If you installed the Unity Hub in a custom path or changed the editor folder location, the task provides a configuration setting in Azure DevOps to specify the path. 

Please let me know, if this helped solve your issue. Thank you for using the extension!

**Comment by vanlecs09** [comment]
It working now, but i got another problem with key signing. Here is editor report:

DisplayProgressbar: Checking prerequisites
Uploading Crash Report
UnityException: Can not sign the application
Unable to sign the application; please provide passwords!. 

Do i need to upload android key to repo?

**Comment by FejZa** [comment]
Please do not use Unity's built in signing for your Android appliation as the build task does not support it yet. Instead use the Azure DevOps "Android Signing" task to sign it. Make sure your publishing settings in your project look like this:

<a href="http://de.tinypic.com?ref=2kea0p" target="_blank"><img src="http://i65.tinypic.com/2kea0p.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

Then configure your pipeline to look something like this:
https://github.com/Dinomite-Studios/unity-build-task/wiki/Android-Pipeline

I am still working on proper documentation and tutorials. I hope this helps.
